### ISSUE TITLE
Couldn't get the code to work?

### ISSUE THREAD

**Issue by ghost** [herjy/MuSCADeT#1]
Hey,

Firstly thank you for making your code publicly available, the results from you code in your paper look fantastic.

So I downloaded the package, and installed as per the readme, but tried to run Example_simple.py, and ran into some problems. I have included the problem below in case that helps. All I did was open Example_simple.py and ran it. Maybe I am doing something stupid, but I can't seem to figure out what I am doing wrong. Any help would be much appreciated.

Andrew

Traceback (most recent call last):
  File "C:\Users\Andrew\Desktop\Install\MuSCADeT\Examples\Example_simple.py", line 25, in <module>
    S,A,Chi = MCA.mMCA(cube, Aprior.T, nsig,n, PCA=[ns,angle], mode=pca)
  File "C:\Users\Andrew\WinPython-64bit-2.7.10.2\python-2.7.10.amd64\lib\site-packages\muscadet-0.1-py2.7.egg\MuSCADeT\MCA.py", line 50, in mMCA
    Apca = PCA_initialise(img.T, PCA[0], angle = PCA[1], mode = 'direct')
TypeError: PCA_initialise() got an unexpected keyword argument 'mode'

**Comment by herjy** [comment]
Hi Andrew, thanks a lot for the interest!
I've recently exeperienced a few issues with my versions. This bug appeared after I removed a few useless options and forgot to clean the code accordingly. 
Now I've updated with a correct version that I've tested here on MAC and Ubuntu. 
Please download the release I've created and try again and feel free to let me know about any issue you may encounter.
Rémy

**Comment by ghost** [comment]
Thanks a lot for your quick response Rémy. I will try the code and let me know if I have any future problems. Thanks for your help.

Andrew
