### ISSUE TITLE
fail to run Example_simple.py directly

### ISSUE THREAD

**Issue by ylilan** [herjy/MuSCADeT#4]
make_colour_sub() requires at least four input Sfile,Afile,Xfile,suffixe, but when executed in Example_simple.py 38-th line, suffixe is missing. Thus user may stuck at that step.

**Comment by herjy** [comment]
That's annoying! Thanks for pointing that bug. This display function is pretty bad anyway, I'll try to patch it today!

**Comment by herjy** [comment]
I addressed the issue in PR #5 
The results are now displayed in a notebook, for a better rendering. Thanks for raising the issue, it was the occasion for me to do some cleanup.

**Comment by ylilan** [comment]
I appreciate your updating :). The SLIT package is also interested  to me.

**Comment by herjy** [comment]
Glad to know that this is of interest to you. The SLIT package is currently under review as well, as it suffers a few bugs and desperately needs a speed up. In the mean time, I can point you towards the Lenstronomy package which is a very robust and well maintained package (I see you already have a fork, great, we are currently looking to integrate SLIT to lenstronomy). On the deblending side, you might also want to check [scarlet](https://github.com/pmelchior/scarlet), which shares similarities with MuSCADeT. Scarlet does not have the freeform capabilities of MuSCADeT yet, but is very well maintained. I. also have a local branch of SCARLET in which I am currently trying to implement the MuSCADeT paradigm.

**Comment by ylilan** [comment]
Thanks for advice, I will also check scarlet.
